# from langchain.tools import tool
# from typing import List, Dict

# @tool
# def get_mock_bloomberg_rss_feeds() -> List[Dict[str, str]]:
#     """Fetch mock Bloomberg RSS news"""
#     data = [{'Headline': 'Asian Stocks Ebb as Global Rally Loses Momentum: Markets Wrap',
#     'Link': 'https://www.bloomberg.com/news/articles/2025-11-27/asian-stocks-to-ebb-as-global-equity-rally-stalls-markets-wrap',
#     'Article': 'Asian stocks wobbled at the open Friday as the sharp rebound in global equities over the past week showed signs of losing momentum.',
#     'Date': '2025-11-27T22:29:53+00:00'},
#     {'Headline': 'Gold Poised for Fourth Monthly Gain on Fed Rate-Cut Optimism',
#     'Link': 'https://www.bloomberg.com/news/articles/2025-11-27/gold-poised-for-fourth-monthly-gain-on-fed-rate-cut-optimism',
#     'Article': 'Gold was steady &mdash; and on track for a fourth monthly gain &mdash; as signs the Federal Reserve will cut rates next month supported the precious metal.',
#     'Date': '2025-11-27T23:44:21+00:00'},
#     {'Headline': 'Oil in Worst Monthly Run Since 2023 With OPEC+, Ukraine in Focus',
#     'Link': 'https://www.bloomberg.com/news/articles/2025-11-27/latest-oil-market-news-and-analysis-for-nov-28',
#     'Article': 'Oil headed for the longest run of monthly losses in more than two years, as traders looked ahead to an OPEC+ meeting this weekend and gauged US-led efforts to end the conflict in Ukraine.',
#     'Date': '2025-11-27T23:33:36+00:00'},
#     {'Headline': 'Vale Boosts Investor Payouts on Strong Output, Iron Ore Prices',
#     'Link': 'https://www.bloomberg.com/news/articles/2025-11-27/vale-boosts-investor-payouts-on-strong-output-iron-ore-prices',
#     'Article': 'Brazilian iron ore heavyweight Vale SA will pay a special dividend to shareholders on the back of its strong operational performance and high prices of the steelmaking ingredient this year.',
#     'Date': '2025-11-27T23:53:06+00:00'},
#     {'Headline': 'China EV Profit Woes Fuel Market Anxiety Over Challenging 2026',
#     'Link': 'https://www.bloomberg.com/news/articles/2025-11-27/china-ev-profit-woes-fuel-market-anxiety-over-challenging-2026',
#     'Article': 'Investors in Chinese electric vehicle stocks had been hoping for a strong earnings season to provide a fresh tailwind. Instead, disappointing results have stoked anxiety about what lies ahead.',
#     'Date': '2025-11-27T23:30:00+00:00'},
#     {'Headline': 'Emerging Assets Halt Rally in Quiet Session Amid US Holiday',
#     'Link': 'https://www.bloomberg.com/news/articles/2025-11-27/china-sets-tone-as-rebound-in-emerging-market-assets-pauses',
#     'Article': 'Emerging-market assets halted their recent advance on Thursday, with a gauge of currencies ending the day little changed and stocks falling slightly amid thin liquidity due to the Thanksgiving holiday.',
#     'Date': '2025-11-27T11:52:17+00:00'},
#     {'Headline': 'How China Came to Dominate Global Shipping Ports',
#     'Link': 'https://www.bloomberg.com/news/videos/2025-11-27/china-s-ports-empire-video',
#     'Article': 'China has invested billions of dollars in building ports around the globe, giving Beijing a strategic advantage as trade tensions rise, and sparking security concerns for the rest of the world.  (Source: Bloomberg)',
#     'Date': '2025-11-27T22:00:03+00:00'},
#     {'Headline': 'OBR Says Reeves Had Favorable UK Forecast Before Tax Speech',
#     'Link': 'https://www.bloomberg.com/news/articles/2025-11-27/uk-s-obr-says-it-had-no-hand-in-tax-u-turn-that-shocked-markets',
#     'Article': 'Rachel Reeves started preparing the public for a manifesto-breaking income-tax rise at the start of November in an unusual pre-budget speech. More surprising was the fact that she did so after privately learning that her fiscal room for maneuver was far better than expected.',
#     'Date': '2025-11-27T15:23:41+00:00'},
#     {'Headline': 'China Halts Some Brazil Soybean Imports Over Contamination',
#     'Link': 'https://www.bloomberg.com/news/articles/2025-11-27/china-halts-some-brazil-soybean-imports-over-contamination',
#     'Article': 'China halted soybean imports from five Brazilian plants owned by major global agricultural firms over sanitation concerns, according to people familiar with the matter.',
#     'Date': '2025-11-27T14:44:51+00:00'},
#     {'Headline': 'Mercuria, Vitol Are Among Bidders for Raizen Argentina Refinery',
#     'Link': 'https://www.bloomberg.com/news/articles/2025-11-27/mercuria-vitol-are-among-bidders-for-raizen-argentina-refinery',
#     'Article': 'Energy trading giants Mercuria Energy Group and Vitol Group are among finalists for a refinery and hundreds of gas stations in Argentina being sold by Raizen SA, according to people familiar with the matter.',
#     'Date': '2025-11-27T19:41:50+00:00'},
#     {'Headline': 'Still Constructive on Chinese Equities, Huynh Says',
#     'Link': 'https://www.bloomberg.com/news/videos/2025-11-27/still-constructive-on-chinese-equities-huynh-says-video',
#     'Article': 'Sophie Huynh, portfolio manager and strategist at BNP Paribas Asset Management, explains why China remains a pocket of diversification in the firm\'s portfolios. She speaks to Lizzy Burden on "Bloomberg Markets." (Source: Bloomberg)',
#     'Date': '2025-11-27T19:06:21+00:00'},
#     {'Headline': 'Hedge Fund Bond Market Bets Risk Yield Spikes, BIS Chief Warns',
#     'Link': 'https://www.bloomberg.com/news/articles/2025-11-27/hedge-fund-bond-market-bets-risk-yield-spikes-bis-chief-warns',
#     'Article': 'Bank for International Settlements head Pablo Hernandez de Cos has added his voice to escalating warnings about the role of non-bank firms including hedge funds in sovereign bond markets, at a time of historic government debt levels and a fraught geopolitical backdrop.',
#     'Date': '2025-11-27T18:30:00+00:00'},
#     {'Headline': 'Anglo-Teck Deal Clears Canada’s National Security Test, Globe Reports',
#     'Link': 'https://www.bloomberg.com/news/articles/2025-11-27/anglo-teck-deal-clears-canada-s-national-security-test-globe-reports',
#     'Article': 'The Canadian government has cleared Anglo American Plc’s proposed takeover of Teck Resources Ltd. on national security grounds, the Globe and Mail reported, removing one hurdle for the two companies to combine.',
#     'Date': '2025-11-27T17:21:22+00:00'},
#     {'Headline': 'Credit Market Can Handle Tech’s Debt Deluge, BI Panelists Say',
#     'Link': 'https://www.bloomberg.com/news/articles/2025-11-27/credit-market-can-handle-tech-s-debt-deluge-bi-panellists-say',
#     'Article': 'Concerns over massive debt issuance from tech giants such as Meta Platforms Inc. and Alphabet Inc. creating oversupply in the credit market are premature, said panelists at the Bloomberg Intelligence European credit market outlook conference in London on Thursday.',
#     'Date': '2025-11-27T17:16:31+00:00'},
#     {'Headline': 'Lenders Line Up for Chile Copper Smelter in Bet Glut Won’t Last',
#     'Link': 'https://www.bloomberg.com/news/articles/2025-11-27/lenders-line-up-for-chile-copper-smelter-in-bet-glut-won-t-last',
#     'Article': 'Chile’s Enami said it has received various financing offers for a $1.7 billion copper smelter and will name the banks to structure the deal as early as next week, even as the market remains depressed.',
#     'Date': '2025-11-27T16:51:29+00:00'},
#     {'Headline': 'Foreign Investment in Canada Falls to Lowest Since Start of ‘24',
#     'Link': 'https://www.bloomberg.com/news/articles/2025-11-27/foreign-investment-in-canada-falls-to-lowest-since-start-of-24',
#     'Article': 'Foreign direct investment into Canada fell in the third quarter, reaching the lowest level in a year and a half.',
#     'Date': '2025-11-27T16:49:38+00:00'},
#     {'Headline': 'European Stocks Head for Muted Finish to November; Puma Rallies',
#     'Link': 'https://www.bloomberg.com/news/articles/2025-11-27/european-stocks-head-for-muted-finish-to-november-puma-rallies',
#     'Article': 'European stocks edged higher on Thursday and were set to close November with a small gain, while Puma SE surged on chatter around a takeover.',
#     'Date': '2025-11-27T08:07:35+00:00'},
#     {'Headline': 'UK Bonds Fall as Budget Relief Gives Way to Longer-Term Concerns',
#     'Link': 'https://www.bloomberg.com/news/articles/2025-11-27/uk-market-declines-offer-reality-check-on-post-budget-relief',
#     'Article': 'UK’s bonds fell, ending a five-day rally, as investors analyzed the economic impact of Chancellor Rachel Reeves’s budget that delayed tax-raising measures until later this decade.',
#     'Date': '2025-11-27T10:56:28+00:00'},
#     {'Headline': 'Moody’s Cuts Brazil’s Raízen to Junk on Rising Debt Levels',
#     'Link': 'https://www.bloomberg.com/news/articles/2025-11-27/brazil-s-raizen-cut-to-junk-by-moody-s-on-worsening-debt-metrics',
#     'Article': 'Moody’s Ratings downgraded sugar powerhouse Raizen SA, cutting to junk one of Brazil’s last remaining investment-grade corporate credits.',
#     'Date': '2025-11-27T13:08:22+00:00'},
#     {'Headline': "Bonds Slip\xa0as Investors Assess the UK's Growth Prospects",
#     'Link': 'https://www.bloomberg.com/news/live-blog/2025-11-27/uk-budget-2025-reeves-tax-hikes-stocks-pound-steady-markets-today',
#     'Article': 'Rachel Reeves presents her budget in Parliament on Nov. 26. Source: UK Parliament',
#     'Date': '2025-11-27T06:48:09+00:00'},
#     {'Headline': 'Allfunds Said to Draw Takeover Interest From Deutsche Boerse',
#     'Link': 'https://www.bloomberg.com/news/articles/2025-11-27/allfunds-said-to-attract-takeover-interest-from-deutsche-boerse',
#     'Article': 'European fund distribution platform Allfunds Group Plc is attracting fresh takeover interest from suitors including Deutsche Boerse AG, according to people familiar with the matter.',
#     'Date': '2025-11-27T15:18:30+00:00'},
#     {'Headline': 'OPEC+ Still on Track to Pause Hikes in Early 2026, Delegates Say',
#     'Link': 'https://www.bloomberg.com/news/articles/2025-11-27/opec-still-on-track-to-pause-hikes-in-early-2026-delegates-say',
#     'Article': 'OPEC+ nations will probably stick with a decision to pause oil production increases in early 2026 when they meet this weekend, delegates said.',
#     'Date': '2025-11-27T15:15:03+00:00'},
#     {'Headline': "Westbourne's Whelan on 2026 Market Outlook and Global Stimulus",
#     'Link': 'https://www.bloomberg.com/news/videos/2025-11-27/westbourne-s-whelan-on-2026-outlook-and-global-stimulus-video',
#     'Article': "Westbourne Research Services Global Macro Strategist, Sharmila Whelan, discusses investment strategies in the context of recent geopolitical and economic developments. She speaks with Bloomberg's Tom Mackenzie on Daybreak Europe. (Source: Bloomberg)",
#     'Date': '2025-11-27T14:21:30+00:00'},
#     {'Headline': 'ECB Officials Saw Rate Level as Robust Enough to Manage Shocks',
#     'Link': 'https://www.bloomberg.com/news/articles/2025-11-27/ecb-officials-saw-rate-level-as-robust-enough-to-manage-shocks',
#     'Article': 'European Central Bank officials saw the existing level of borrowing costs as sufficient to deal with possible jolts to the economic outlook, according to an account of their October meeting.',
#     'Date': '2025-11-27T12:57:18+00:00'},
#     {'Headline': 'South Africa Corn Crop Rises to Second Largest on Record on Rain',
#     'Link': 'https://www.bloomberg.com/news/articles/2025-11-27/south-africa-corn-crop-rises-to-second-largest-on-record-on-rain',
#     'Article': 'South African farmers probably produced the second-biggest corn crop on record in 2025 as the country experienced good rains earlier in the year.',
#     'Date': '2025-11-27T12:56:38+00:00'}]

#     return data[:3]