from langchain.tools import tool
from typing import List, Dict, Any

@tool
async def mock_process_bloomberg_news() -> List[Dict[str, Any]]:
    """Mock process Bloomberg RSS news"""
    data = [{'Industry': 'General Market',
    'Date': '2025-11-27T22:29:53+00:00',
    'News': [{'Headline': 'Asian Stocks Ebb as Global Rally Loses Momentum: Markets Wrap',
        'Date': '2025-11-27T22:29:53+00:00',
        'Link': 'https://www.bloomberg.com/news/articles/2025-11-27/asian-stocks-to-ebb-as-global-equity-rally-stalls-markets-wrap',
        'Article': 'Asian stocks wobbled at the open Friday as the sharp rebound in global equities over the past week showed signs of losing momentum.',
        'SentimentScore': 0.0039989622,
        'Industry': 'General Market'}],
    'ArticleCount': 1,
    'ImpactfulNews': [{'Headline': 'Asian Stocks Ebb as Global Rally Loses Momentum: Markets Wrap',
        'Article': 'Asian stocks wobbled at the open Friday as the sharp rebound in global equities over the past week showed signs of losing momentum.',
        'SentimentScore': 0.0039989622}],
    'AvgSentimentScore': 0.0039989622,
    'SentimentScore': 0.001944202,
    'SentimentExplanation': 'Explanation: The FinBERT score around 0.002–0.004 indicates a near-neutral sentiment for the general market. The article notes Asian equities wobbling as the global rally loses momentum, suggesting cautious investor posture and limited near-term directional moves as markets await clearer catalysts.'},
    {'Industry': 'Financials',
    'Date': '2025-11-27T23:33:36+00:00',
    'News': [{'Headline': 'Oil in Worst Monthly Run Since 2023 With OPEC+, Ukraine in Focus',
        'Date': '2025-11-27T23:33:36+00:00',
        'Link': 'https://www.bloomberg.com/news/articles/2025-11-27/latest-oil-market-news-and-analysis-for-nov-28',
        'Article': 'Oil headed for the longest run of monthly losses in more than two years, as traders looked ahead to an OPEC+ meeting this weekend and gauged US-led efforts to end the conflict in Ukraine.',
        'SentimentScore': -0.008944381,
        'Industry': 'Financials'}],
    'ArticleCount': 1,
    'ImpactfulNews': [{'Headline': 'Oil in Worst Monthly Run Since 2023 With OPEC+, Ukraine in Focus',
        'Article': 'Oil headed for the longest run of monthly losses in more than two years, as traders looked ahead to an OPEC+ meeting this weekend and gauged US-led efforts to end the conflict in Ukraine.',
        'SentimentScore': -0.008944381}],
    'AvgSentimentScore': -0.008944381,
    'SentimentScore': 0.0028017424,
    'SentimentExplanation': "The FinBERT sentiment score is approximately -0.009, i.e., near neutral with a slight negative tilt. This reflects the article's emphasis on oil's continued monthly losses and the uncertainty around OPEC+ decisions and the Ukraine conflict. While the energy sector could face near-term volatility, the near-zero score suggests a modest, not overpowering, impact on financial markets in the Financials space; investors may stay cautious ahead of policy meetings, watching for any signs of supply-tightening or conflict de-escalation that could shift oil demand expectations."},
    {'Industry': 'Financials',
    'Date': '2025-11-27T23:44:21+00:00',
    'News': [{'Headline': 'Gold Poised for Fourth Monthly Gain on Fed Rate-Cut Optimism',
        'Date': '2025-11-27T23:44:21+00:00',
        'Link': 'https://www.bloomberg.com/news/articles/2025-11-27/gold-poised-for-fourth-monthly-gain-on-fed-rate-cut-optimism',
        'Article': 'Gold was steady &mdash; and on track for a fourth monthly gain &mdash; as signs the Federal Reserve will cut rates next month supported the precious metal.',
        'SentimentScore': -0.8583589792,
        'Industry': 'Financials'}],
    'ArticleCount': 1,
    'ImpactfulNews': [{'Headline': 'Gold Poised for Fourth Monthly Gain on Fed Rate-Cut Optimism',
        'Article': 'Gold was steady &mdash; and on track for a fourth monthly gain &mdash; as signs the Federal Reserve will cut rates next month supported the precious metal.',
        'SentimentScore': -0.8583589792}],
    'AvgSentimentScore': -0.8583589792,
    'SentimentScore': -0.8677232862,
    'SentimentExplanation': 'The article carries a strong negative FinBERT sentiment (-0.858), indicating traders view it as unfavorable to financials in the near term. While gold benefits from Fed rate-cut expectations, the piece frames that environment as potentially dampening bank net interest margins and financial sector profitability, which drags sentiment in the Financials industry even as the commodity side improves.'}]

    return data